// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/student/student.proto

package go_micro_srv_student

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Student struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_3efdffaa3afda52d, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3efdffaa3afda52d, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool       `protobuf:"varint,1,opt,name=Created,proto3" json:"Created,omitempty"`
	Student              *Student   `protobuf:"bytes,2,opt,name=student,proto3" json:"student,omitempty"`
	Students             []*Student `protobuf:"bytes,3,rep,name=students,proto3" json:"students,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3efdffaa3afda52d, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

func (m *Response) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

func init() {
	proto.RegisterType((*Student)(nil), "go.micro.srv.student.Student")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.student.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.student.Response")
}

func init() { proto.RegisterFile("proto/student/student.proto", fileDescriptor_3efdffaa3afda52d) }

var fileDescriptor_3efdffaa3afda52d = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x34, 0xbb, 0xda, 0x5d, 0x9f, 0x5a, 0xe4, 0xe1, 0x21, 0x28, 0x4a, 0xc8, 0xa9, 0xa7, 0x08,
	0xf5, 0x20, 0x9e, 0x44, 0x3c, 0xf4, 0xe2, 0x41, 0xd2, 0x2f, 0x58, 0xbb, 0x8f, 0x12, 0x68, 0x37,
	0x35, 0x49, 0xfb, 0x2d, 0x7e, 0x86, 0x9f, 0x28, 0x66, 0x13, 0xbd, 0x2c, 0xed, 0x29, 0x93, 0x79,
	0x93, 0x61, 0x32, 0x0f, 0x6e, 0x36, 0xce, 0x06, 0x7b, 0xef, 0xc3, 0xb6, 0xa5, 0x2e, 0xe4, 0x53,
	0x45, 0x16, 0xaf, 0x96, 0x56, 0xad, 0xcd, 0xc2, 0x59, 0xe5, 0xdd, 0x4e, 0xa5, 0x99, 0x7c, 0x86,
	0x6a, 0xde, 0x43, 0x1c, 0x43, 0x61, 0x5a, 0xce, 0x04, 0x9b, 0x9c, 0xea, 0xc2, 0xb4, 0x88, 0x70,
	0xdc, 0x35, 0x6b, 0xe2, 0x45, 0x64, 0x22, 0xc6, 0x4b, 0x28, 0x9b, 0x25, 0xf1, 0x52, 0xb0, 0xc9,
	0x89, 0xfe, 0x85, 0xf2, 0x1c, 0x60, 0x46, 0x41, 0xd3, 0xe7, 0x96, 0x7c, 0x90, 0x5f, 0x0c, 0x6a,
	0x4d, 0x7e, 0x63, 0x3b, 0x4f, 0xc8, 0xa1, 0x7a, 0x75, 0xd4, 0x04, 0xea, 0x5d, 0x6b, 0x9d, 0xaf,
	0xf8, 0x08, 0x55, 0x0a, 0x10, 0xdd, 0xcf, 0xa6, 0xb7, 0x6a, 0x28, 0x9d, 0x4a, 0xd1, 0x74, 0x56,
	0xe3, 0x13, 0xd4, 0x09, 0x7a, 0x5e, 0x8a, 0xf2, 0xf0, 0xcb, 0x3f, 0xf9, 0xf4, 0x9b, 0xc1, 0x38,
	0xb1, 0x73, 0x72, 0x3b, 0xb3, 0x20, 0x7c, 0x87, 0x8b, 0x3e, 0x51, 0xae, 0x60, 0xbf, 0xd9, 0xf5,
	0xdd, 0xf0, 0x38, 0x7f, 0x58, 0x1e, 0xe1, 0x1b, 0x8c, 0x66, 0x14, 0x5e, 0x56, 0x2b, 0x14, 0xc3,
	0xda, 0xff, 0xae, 0x0e, 0xbb, 0x7d, 0x8c, 0xe2, 0xe6, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x67, 0x3b, 0xa9, 0x25, 0xd8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	CreateStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error)
}

type studentServiceClient struct {
	cc *grpc.ClientConn
}

func NewStudentServiceClient(cc *grpc.ClientConn) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) CreateStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.student.StudentService/CreateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetAll(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/go.micro.srv.student.StudentService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	CreateStudent(context.Context, *Student) (*Response, error)
	GetAll(context.Context, *GetRequest) (*Response, error)
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.student.StudentService/CreateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).CreateStudent(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.student.StudentService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetAll(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.student.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStudent",
			Handler:    _StudentService_CreateStudent_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _StudentService_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/student/student.proto",
}
